:feat Change display to print competencies and education on two disti…
maxds-lyon/lokiprint pull request #11
Opened 2024-05-15 15:16 UTC by kdelfour

…nct pages

2024-05-15 15:32 UTC, almarzn requested changes

2024-05-15 15:32 UTC, almarzn commented on templates/typst/.template/shared/sizes.typ
> +#let perfect-fourth-scale = size-scale.with(ratio: 1.35)
pourquoi tu as changé ces lignes? normalement tu devrais pas change ça

2024-05-15 15:32 UTC, almarzn commented on templates/typst/main.typ
> +    #block(inset: (x: 24pt, top: 48pt), flex(
Je préfèrerais que tu utilise le param breakable sur le block education :

https://typst.app/docs/reference/layout/block/#parameters-breakable

2024-05-15 15:32 UTC, almarzn commented on Dockerfile
> +RUN apk add typst --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
C'est comme ça que tu as fait le fixe ?

2024-05-15 15:42 UTC, kdelfour commented on Dockerfile
> +RUN apk add typst --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
J'ai essayé, j'ai eu plus de build qui sont passés mais toujours des erreurs aléatoires

2024-05-15 15:47 UTC, kdelfour commented on templates/typst/main.typ
> +    #block(inset: (x: 24pt, top: 48pt), flex(
Oui mais non, sinon j'ai des soucis de break avec le titre sur la premiere page et le reste sur la deuxième page
![image](https://github.com/maxds-lyon/lokiprint/assets/1392697/db16461d-fe4d-4d4c-b90f-6f84427769b4)

2024-06-14 08:57 UTC, almarzn commented on templates/typst/main.typ
> +    #block(inset: (x: 24pt, top: 48pt), flex(
et pourquoi tu ne mets pas le titre dans un block?

2024-07-19 09:24 UTC, closed without merging