refacto createPublish
maxds-lyon/lokiprint pull request #7
Opened 2024-03-28 16:08 UTC by juliengiraud

2024-03-28 16:21 UTC, almarzn requested changes

2024-03-28 16:21 UTC, almarzn commented on createPublish.mjs
> +    function invalideFileTreatment(file, data) {
Peux tu renommer ça en printYamlErrors stp ?

2024-03-28 16:21 UTC, almarzn commented on createPublish.mjs
> +    async function doPublish() {
A la limite est-ce que tu ne pourrais pas unwrapper pour le mettre dans la fonction principale ?

2024-03-28 16:21 UTC, almarzn commented on createPublish.mjs
> +    async function extractOutputFromTemplate({ template, data, templateWorkdir, item, simpleItem }) {
La fonction execute le rendu du template aussi :)

2024-03-28 16:21 UTC, almarzn commented on createPublish.mjs
> +        if (item != simpleItem) {
Tu as oublié un égal, et je ne comprends pas à quoi sert cette condition

2024-03-28 16:21 UTC, almarzn commented on createPublish.mjs
> +            yamlFiles.map(async (file) => processFile(file))
Pas besoin de async ici, vu que tu n'utilise pas await. Le fait que processFile retourne une promesses suffit

2024-03-28 16:34 UTC, juliengiraud commented on createPublish.mjs
> +    async function doPublish() {
c'est à dire passer de ça :
```js
    async function doPublish() {
        console.log(chalk.green('Loaded template functions [' + templateFunctions.map(it => it.id).join(", ") + ']'));
        return processFiles();
    }
    return doPublish();
```
à ça ?
```js
    console.log(chalk.green('Loaded template functions [' + templateFunctions.map(it => it.id).join(", ") + ']'));
    return processFiles();
```

2024-03-28 16:37 UTC, juliengiraud commented on createPublish.mjs
> +        if (item != simpleItem) {
ah bien joué c'était un oublie de quand j'avais le paramètre watch

2024-03-28 16:37 UTC, almarzn commented on createPublish.mjs
> +    async function doPublish() {
oui

2024-03-28 16:38 UTC, juliengiraud commented on createPublish.mjs
> +            yamlFiles.map(async (file) => processFile(file))
sur la ligne du map uniquement c'est bien ça ?

2024-03-29 09:19 UTC, almarzn commented on createPublish.mjs
> +            yamlFiles.map(async (file) => processFile(file))
oui :)

2024-03-29 09:21 UTC, almarzn approved these changes
C'est bon pour moi, penses à squash avant de merge stp :)

2024-03-29 09:55 UTC, merged